### ISSUE TITLE
Can't install python 3.5

### ISSUE THREAD

**Issue by benigls** [Stouts/Stouts.python#3]
I'm trying to install python 3.5 using the `python_version` variable from the playbook vars.

```

---
 - hosts: all
   sudo: yes
   user: root
   roles:
     - Stouts.python
   vars:
     python_version: [3.5, ]
     python_install: [virtualenvwrapper, ]
```

But it seems that it doesn't install the python 3.5 when I run it.

```
...
TASK: [Stouts.python | Install python] **************************************** 
ok: [000.000.000.00] => (item=2.7)
ok: [000.000.000.00] => (item=3.4)

TASK: [Stouts.python | Install python-dev] ************************************ 
ok: [000.000.000.00] => (item=2.7)
ok: [000.000.000.00] => (item=3.4)
...
```

I have to manually insert the `3.5` to the `default/main.yml` to install it.

```
...
TASK: [Stouts.python | Install python] **************************************** 
ok: [000.000.000.00] => (item=2.7)
ok: [000.000.000.00] => (item=3.4)
changed: [000.000.000.00] => (item=3.5)

TASK: [Stouts.python | Install python-dev] ************************************ 
ok: [000.000.000.00] => (item=2.7)
ok: [000.000.000.00] => (item=3.4)
changed: [000.000.000.00] => (item=3.5)
...
```

**Comment by skolsuper** [comment]
@benigls I know this is late, but did you try `python_versions` (note the 's')?

**Comment by avelis** [comment]
@benigls 
Have you tried the following?
```yaml
   vars:
     python_versions: [3.5]
     python_install: [virtualenvwrapper]
```
